### PR TITLE
Fix base_url variable when editing a collection

### PR DESCRIPTION
**Pull request by rodfersou**

### CODE REVIEW

**Comment by rodfersou** [comment]
related to: https://github.com/plone/plone.app.layout/pull/87

**Comment by rodfersou** [comment]
Related to: https://github.com/plone/plone.app.layout/pull/87/files

**Comment by jensens** [comment]
You can always start a Jenkins test-job on your own to test that your pull request (PR) does not break anything. 

Below click on the link to Jenkins
screenshot from 2016-07-25 11 20 06

**log in** with your Github user - if not already done before.

Paste the full **pull request URL** into the text field (if multiple pull requests need to be combined in one run, then one PR URL per line)

Click on **Build**

Jenkins reports back to the pull request(s) on Github in the status box at the bottom.

In Plone we value a lot our testing suite, so we usually never merge pull requests if they have not been tested by Jenkins first.

**Comment by rodfersou** [comment]
Hi @jensens thank you for your advise, done

**Comment by rodfersou** [comment]
@jensens the problem was that I was pasting the URL https://github.com/plone/archetypes.querywidget/pull/13/files instead of https://github.com/plone/archetypes.querywidget/pull/13

I think it worked before with the /files in the end..

**Comment by rodfersou** [comment]
@jensens @hvelarde green :smile:

**Comment by jensens** [comment]
thanks!

**Pull request merged**
