### PR TITLE
Added 'safe_unicode' call for raw query values

### PR DESCRIPTION
**Pull request by rodfersou**

### CODE REVIEW

**Comment by tisto** [comment]
http://jenkins.plone.org/job/pull-request/107/

**Comment by tisto** [comment]
Ok. The Jenkins job will not work. This is for Plone 4.3.

**Comment by rodfersou** [comment]
@tisto I think this fix should be applied in both Plone 4.3 and Plone 5.0

**Comment by rodfersou** [comment]
@tisto should I change buildout.coredev to checkout archetypes.querywidget ? I'm not sure if jenkins is looking at my changes

**Comment by tisto** [comment]
I will take care of that. We are working on new Plone releases right now.

**Comment by rodfersou** [comment]
nice!

**Comment by gforcada** [comment]
@tisto there's http://jenkins.plone.org/view/All/job/pull-request-4.3/ to test pull request targeting Plone 4.3, I have to move it to the Core tab and blog about it sooner or later. Thinks are piling up! :)

**Comment by tisto** [comment]
@gforcada Awesome! Though, I think the pull request jobs should go to a separate tab. If people (like me) want to use the view to check the overall build status of jenkins (desktop integration).

**Comment by rodfersou** [comment]
@tisto this will get into the new releases?

**Comment by tisto** [comment]
Testing pull request against Plone 4.3: http://jenkins.plone.org/view/All/job/pull-request-4.3/10/

**Comment by rodfersou** [comment]
@tisto thank you!

**Comment by hvelarde** [comment]
@tisto can you help me identifying the source of the error in Jenkins?

**Comment by tisto** [comment]
@hvelarde sure. will have a look...

**Comment by tisto** [comment]
@hvelarde Both robot test that fail (plone.app.dexterity and plone.schemaeditor) are fragile and written in a bad way (e.g. the go to a url and click on an element before making sure that element has been fully loaded). It might help to re-write them to work more reliably. The plone.schemaeditor tests for instance are a constant pain. Though, it is strange that they just fail on the pr job.

http://jenkins.plone.org/view/All/job/pull-request-4.3/13/robot/report/robot_log.html#s1-s10

**Comment by hvelarde** [comment]
@rodfersou could you please take a look at the failing test tomorrow?

**Comment by rodfersou** [comment]
@hvelarde sure

**Comment by rodfersou** [comment]
starting jenkins again http://jenkins.plone.org/job/pull-request-4.3/132/

**Comment by rodfersou** [comment]
@hvelarde @tisto @gforcada green light here

**Pull request merged**
